linters:
  enable-all: false
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - unused
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - staticcheck

  linters-settings:
    errcheck:
      ignore: ''
      exclude-functions:
       - fmt:.*

run:
  tests: false