// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"encoding/json"
)

const TableNameGoods = "ydd_goods"

// Goods 商品表
type Goods struct {
	GoodsID            int32   `gorm:"column:goods_id;primaryKey;autoIncrement:true;comment:商品id" json:"goods_id"`                                  // 商品id
	GoodsName          string  `gorm:"column:goods_name;not null;comment:商品名称" json:"goods_name"`                                                   // 商品名称
	GoodsClass         int32   `gorm:"column:goods_class;not null;default:1;comment:商品种类1.实物商品2.虚拟商品3.卡券商品" json:"goods_class"`                     // 商品种类1.实物商品2.虚拟商品3.卡券商品
	GoodsClassName     string  `gorm:"column:goods_class_name;not null;comment:商品种类" json:"goods_class_name"`                                       // 商品种类
	GoodsAttrClass     int32   `gorm:"column:goods_attr_class;not null;default:1;comment:商品类型id" json:"goods_attr_class"`                           // 商品类型id
	GoodsAttrName      string  `gorm:"column:goods_attr_name;not null;comment:商品类型名称" json:"goods_attr_name"`                                       // 商品类型名称
	SiteID             int32   `gorm:"column:site_id;not null;comment:所属店铺id" json:"site_id"`                                                       // 所属店铺id
	SiteName           string  `gorm:"column:site_name;not null;comment:所属店铺名称" json:"site_name"`                                                   // 所属店铺名称
	GoodsImage         string  `gorm:"column:goods_image;not null;comment:商品主图路径" json:"goods_image"`                                               // 商品主图路径
	GoodsContent       string  `gorm:"column:goods_content;comment:商品详情" json:"goods_content"`                                                      // 商品详情
	GoodsState         int32   `gorm:"column:goods_state;not null;comment:商品状态（1.正常0下架）" json:"goods_state"`                                        // 商品状态（1.正常0下架）
	CategoryID         string  `gorm:"column:category_id;not null;comment:商品分类id,逗号隔开" json:"category_id"`                                          // 商品分类id,逗号隔开
	CategoryJSON       string  `gorm:"column:category_json;not null;comment:分类json字符串" json:"category_json"`                                        // 分类json字符串
	Price              float64 `gorm:"column:price;not null;default:0.00;comment:商品价格（取第一个sku）" json:"price"`                                       // 商品价格（取第一个sku）
	MarketPrice        float64 `gorm:"column:market_price;not null;default:0.00;comment:划线价格（取第一个sku）" json:"market_price"`                         // 划线价格（取第一个sku）
	CostPrice          float64 `gorm:"column:cost_price;not null;default:0.00;comment:成本价（取第一个sku）" json:"cost_price"`                              // 成本价（取第一个sku）
	GoodsStock         int32   `gorm:"column:goods_stock;not null;comment:商品库存（总和）" json:"goods_stock"`                                             // 商品库存（总和）
	GoodsStockAlarm    int32   `gorm:"column:goods_stock_alarm;not null;comment:库存预警" json:"goods_stock_alarm"`                                     // 库存预警
	IsVirtual          int32   `gorm:"column:is_virtual;not null;comment:是否虚拟类商品（0实物1.虚拟）" json:"is_virtual"`                                       // 是否虚拟类商品（0实物1.虚拟）
	VirtualIndate      int32   `gorm:"column:virtual_indate;not null;default:1;comment:虚拟商品有效期" json:"virtual_indate"`                              // 虚拟商品有效期
	IsFreeShipping     int32   `gorm:"column:is_free_shipping;not null;comment:是否免邮" json:"is_free_shipping"`                                       // 是否免邮
	ShippingTemplate   int32   `gorm:"column:shipping_template;not null;comment:指定运费模板" json:"shipping_template"`                                   // 指定运费模板
	GoodsSpecFormat    string  `gorm:"column:goods_spec_format;comment:商品规格格式" json:"goods_spec_format"`                                            // 商品规格格式
	GoodsAttrFormat    string  `gorm:"column:goods_attr_format;comment:商品属性格式" json:"goods_attr_format"`                                            // 商品属性格式
	IsDelete           int32   `gorm:"column:is_delete;not null;comment:是否已经删除" json:"is_delete"`                                                   // 是否已经删除
	Introduction       string  `gorm:"column:introduction;not null;comment:促销语" json:"introduction"`                                                // 促销语
	Keywords           string  `gorm:"column:keywords;not null;comment:关键词" json:"keywords"`                                                        // 关键词
	Unit               string  `gorm:"column:unit;not null;comment:单位" json:"unit"`                                                                 // 单位
	Sort               int32   `gorm:"column:sort;not null;comment:排序" json:"sort"`                                                                 // 排序
	CreateTime         uint    `gorm:"column:create_time;not null;autoCreateTime;comment:创建时间" json:"create_time"`                                  // 创建时间
	ModifyTime         int32   `gorm:"column:modify_time;not null;comment:修改时间" json:"modify_time"`                                                 // 修改时间
	VideoURL           string  `gorm:"column:video_url;not null;comment:视频" json:"video_url"`                                                       // 视频
	SaleNum            int32   `gorm:"column:sale_num;not null;comment:销量" json:"sale_num"`                                                         // 销量
	Evaluate           int32   `gorm:"column:evaluate;not null;comment:评价数" json:"evaluate"`                                                        // 评价数
	EvaluateShaitu     int32   `gorm:"column:evaluate_shaitu;not null;comment:评价晒图数" json:"evaluate_shaitu"`                                        // 评价晒图数
	EvaluateShipin     int32   `gorm:"column:evaluate_shipin;not null;comment:评价视频数" json:"evaluate_shipin"`                                        // 评价视频数
	EvaluateZhuiping   int32   `gorm:"column:evaluate_zhuiping;not null;comment:评价追评数" json:"evaluate_zhuiping"`                                    // 评价追评数
	EvaluateHaoping    int32   `gorm:"column:evaluate_haoping;not null;comment:评价好评数" json:"evaluate_haoping"`                                      // 评价好评数
	EvaluateZhongping  int32   `gorm:"column:evaluate_zhongping;not null;comment:评价中评数" json:"evaluate_zhongping"`                                  // 评价中评数
	EvaluateChaping    int32   `gorm:"column:evaluate_chaping;not null;comment:评价差评数" json:"evaluate_chaping"`                                      // 评价差评数
	IsFenxiao          bool    `gorm:"column:is_fenxiao;not null;comment:参与分销（0不参与 1参与）" json:"is_fenxiao"`                                         // 参与分销（0不参与 1参与）
	FenxiaoType        bool    `gorm:"column:fenxiao_type;not null;default:1;comment:分销佣金类型（1默认  2自行设置）" json:"fenxiao_type"`                       // 分销佣金类型（1默认  2自行设置）
	SupplierID         int32   `gorm:"column:supplier_id;not null;comment:供应商id" json:"supplier_id"`                                                // 供应商id
	IsConsumeDiscount  bool    `gorm:"column:is_consume_discount;not null;comment:是否参与会员等级折扣" json:"is_consume_discount"`                           // 是否参与会员等级折扣
	DiscountConfig     bool    `gorm:"column:discount_config;not null;comment:优惠设置（0默认 1自定义）" json:"discount_config"`                               // 优惠设置（0默认 1自定义）
	DiscountMethod     string  `gorm:"column:discount_method;not null;comment:优惠方式（discount打折 manjian 满减 fixed_price 指定价格）" json:"discount_method"` // 优惠方式（discount打折 manjian 满减 fixed_price 指定价格）
	SkuID              int32   `gorm:"column:sku_id;not null;comment:sku_id" json:"sku_id"`                                                         // sku_id
	PromotionAddon     string  `gorm:"column:promotion_addon;not null;comment:当前参与的营销活动，逗号分隔（限时折扣、团购、拼团、秒杀、专题活动）" json:"promotion_addon"`           // 当前参与的营销活动，逗号分隔（限时折扣、团购、拼团、秒杀、专题活动）
	GoodsServiceIds    string  `gorm:"column:goods_service_ids;not null;comment:商品服务id" json:"goods_service_ids"`                                   // 商品服务id
	LabelID            string  `gorm:"column:label_id;not null;comment:商品分组id" json:"label_id"`                                                     // 商品分组id
	VirtualSale        int32   `gorm:"column:virtual_sale;not null;comment:虚拟销量" json:"virtual_sale"`                                               // 虚拟销量
	MaxBuy             int32   `gorm:"column:max_buy;not null;comment:限购" json:"max_buy"`                                                           // 限购
	MinBuy             int32   `gorm:"column:min_buy;not null;comment:起购数" json:"min_buy"`                                                          // 起购数
	RecommendWay       int32   `gorm:"column:recommend_way;not null;comment:推荐方式，1：新品，2：精品，3；推荐" json:"recommend_way"`                              // 推荐方式，1：新品，2：精品，3；推荐
	TimerOn            int32   `gorm:"column:timer_on;not null;comment:定时上架" json:"timer_on"`                                                       // 定时上架
	TimerOff           int32   `gorm:"column:timer_off;not null;comment:定时下架" json:"timer_off"`                                                     // 定时下架
	IsNeedVerify       int32   `gorm:"column:is_need_verify;not null;comment:是否需要核销" json:"is_need_verify"`                                         // 是否需要核销
	VerifyValidityType int32   `gorm:"column:verify_validity_type;not null;comment:核销有效期类型 0：永久有效 1：购买后x天有效 2：指定过期日期" json:"verify_validity_type"`  // 核销有效期类型 0：永久有效 1：购买后x天有效 2：指定过期日期
	IsLimit            int32   `gorm:"column:is_limit;not null;comment:商品是否限购(0:否 1:是)" json:"is_limit"`                                            // 商品是否限购(0:否 1:是)
	LimitType          int32   `gorm:"column:limit_type;not null;default:1;comment:限购类型(1:单次限购 2:长期限购)" json:"limit_type"`                          // 限购类型(1:单次限购 2:长期限购)
	LimitTime          int32   `gorm:"column:limit_time;not null;comment:限购秒数(0为长期限购)" json:"limit_time"`                                           // 限购秒数(0为长期限购)
	QrID               int32   `gorm:"column:qr_id;not null;comment:社群二维码id" json:"qr_id"`                                                          // 社群二维码id
	TemplateID         int32   `gorm:"column:template_id;not null;comment:海报id" json:"template_id"`                                                 // 海报id
	SuccessEvaluateNum int32   `gorm:"column:success_evaluate_num;not null;comment:评价审核通过数" json:"success_evaluate_num"`                            // 评价审核通过数
	FailEvaluateNum    int32   `gorm:"column:fail_evaluate_num;not null;comment:评价审核失败数" json:"fail_evaluate_num"`                                  // 评价审核失败数
	WaitEvaluateNum    int32   `gorm:"column:wait_evaluate_num;not null;comment:评价待审核数" json:"wait_evaluate_num"`                                   // 评价待审核数
	GoodsErpSpid       string  `gorm:"column:goods_erp_spid;not null;default:0;comment:erp商品唯一标识" json:"goods_erp_spid"`                            // erp商品唯一标识
	IsKongxiao         int32   `gorm:"column:is_kongxiao;not null;comment:是否控销产品 0:不是 1：是--可删除、需清除代码" json:"is_kongxiao"`                           // 是否控销产品 0:不是 1：是--可删除、需清除代码
	IsSyncGoodsState   int32   `gorm:"column:is_sync_goods_state;not null;default:1;comment:是否自动上下架 0:不是 1：是" json:"is_sync_goods_state"`           // 是否自动上下架 0:不是 1：是
	GoodsArea          string  `gorm:"column:goods_area;comment:商品对应erp的库区" json:"goods_area"`                                                      // 商品对应erp的库区
	GoodsAreaID        int32   `gorm:"column:goods_area_id;not null;comment:库存id" json:"goods_area_id"`                                             // 库存id
	BarCode            string  `gorm:"column:bar_code;comment:商品条码" json:"bar_code"`                                                                // 商品条码
	GoodsNum           string  `gorm:"column:goods_num;comment:商品编码" json:"goods_num"`                                                              // 商品编码
	BusinessScope      string  `gorm:"column:business_scope;comment:商品属于的经营范围" json:"business_scope"`                                               // 商品属于的经营范围
	BusinessScopeName  string  `gorm:"column:business_scope_name;not null;comment:商品属于的经营范围名称" json:"business_scope_name"`                          // 商品属于的经营范围名称
	Manufactor         string  `gorm:"column:manufactor;not null;comment:生产厂家 [new]" json:"manufactor"`                                             // 生产厂家 [new]
	GoodsFlag          string  `gorm:"column:goods_flag;not null;comment:ERP字段 GOODS_FLAG--可删除、需清除代码" json:"goods_flag"`                            // ERP字段 GOODS_FLAG--可删除、需清除代码
	Packsize           int32   `gorm:"column:packsize;not null;default:1;comment:件装量" json:"packsize"`                                              // 件装量
	Currencyname       string  `gorm:"column:currencyname;not null;comment:商品名" json:"currencyname"`                                                // 商品名
	AttrDosageForm     string  `gorm:"column:attr_dosage_form;not null;comment:剂型" json:"attr_dosage_form"`                                         // 剂型
	InventoryDisplay   string  `gorm:"column:inventory_display;comment:新增：库存显示" json:"inventory_display"`                                           // 新增：库存显示
	PriceSync          int32   `gorm:"column:price_sync;not null;default:1;comment:是否同步价格" json:"price_sync"`                                       // 是否同步价格
	StockSync          int32   `gorm:"column:stock_sync;not null;default:1;comment:是否同步库存" json:"stock_sync"`                                       // 是否同步库存
	MinBuySync         int32   `gorm:"column:min_buy_sync;not null;default:1;comment:是否同步中包装" json:"min_buy_sync"`                                  // 是否同步中包装
	IsPresale          int32   `gorm:"column:is_presale;not null;comment:是否预售 （暂时弃用）" json:"is_presale"`                                            // 是否预售 （暂时弃用）
	OffSalesLabelIds   string  `gorm:"column:off_sales_label_ids;not null;comment:禁止销售的会员类型id列表，为空则不限制" json:"off_sales_label_ids"`                 // 禁止销售的会员类型id列表，为空则不限制
	OffReason          string  `gorm:"column:off_reason;not null;comment:下架原因" json:"off_reason"`                                                   // 下架原因
	TaxRate            float64 `gorm:"column:tax_rate;not null;default:0.00;comment:税率 单位:百分比" json:"tax_rate"`                                     // 税率 单位:百分比
	ExtensionData      string  `gorm:"column:extension_data;comment:拓展属性，同属，只是格式不同" json:"extension_data"`                                          // 拓展属性，同属，只是格式不同
	BrandID            int32   `gorm:"column:brand_id;not null;comment:品牌id" json:"brand_id"`                                                       // 品牌id
	BrandName          string  `gorm:"column:brand_name;not null;comment:品牌名称" json:"brand_name"`                                                   // 品牌名称
	QixieZilei         int32   `gorm:"column:qixie_zilei;comment:器械子类 两位数字" json:"qixie_zilei"`                                                     // 器械子类 两位数字
	Gspflag            int32   `gorm:"column:gspflag;not null;default:1;comment:GSP管控 1=管控" json:"gspflag"`                                         // GSP管控 1=管控
	SalesmanIsJoin     bool    `gorm:"column:salesman_is_join;not null;default:1;comment:业务员是否参与（0不参与 1参与）" json:"salesman_is_join"`                // 业务员是否参与（0不参与 1参与）
	GoodsLabel         string  `gorm:"column:goods_label;comment:处方药类别" json:"goods_label"`                                                         // 处方药类别
	YibaoType          string  `gorm:"column:yibao_type;comment:医保类别" json:"yibao_type"`                                                            // 医保类别
	YibaoNo            string  `gorm:"column:yibao_no;comment:医保编码" json:"yibao_no"`                                                                // 医保编码
	IsMedicinal        int32   `gorm:"column:is_medicinal;not null;comment:是否中药，0=否 1=是" json:"is_medicinal"`                                       // 是否中药，0=否 1=是
	ProductData        string  `gorm:"column:product_data;comment:产品资料" json:"product_data"`                                                        // 产品资料
	InspectionData     string  `gorm:"column:inspection_data;comment:检验报告" json:"inspection_data"`                                                  // 检验报告
	TraceabilityCode   int32   `gorm:"column:traceability_code;not null;comment:追溯码，0=否 1=是" json:"traceability_code"`                              // 追溯码，0=否 1=是
	DzjgCode           int32   `gorm:"column:dzjg_code;not null;comment:电子监管码标志，0=否 1=是" json:"dzjg_code"`                                          // 电子监管码标志，0=否 1=是
	IsJc               int32   `gorm:"column:is_jc;not null;comment:是否集采，0=否 1=是" json:"is_jc"`                                                     // 是否集采，0=否 1=是
	SyncImageTime      int32   `gorm:"column:sync_image_time;not null;comment:商品图片同步时间" json:"sync_image_time"`                                     // 商品图片同步时间
	AutoOut            int32   `gorm:"column:auto_out;not null;comment:0未处理 1自动下架" json:"auto_out"`                                                 // 0未处理 1自动下架
}

// MarshalBinary 支持json序列化
func (m *Goods) MarshalBinary() (data []byte, err error) {
	return json.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *Goods) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

// TableName Goods's table name
func (*Goods) TableName() string {
	return TableNameGoods
}
