// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"encoding/json"
)

const TableNameOrderGoods = "ydd_order_goods"

// OrderGoods 订单商品表
type OrderGoods struct {
	OrderGoodsID         int32   `gorm:"column:order_goods_id;primaryKey;autoIncrement:true" json:"order_goods_id"`
	OrderID              int32   `gorm:"column:order_id;not null;comment:订单id" json:"order_id"`                                                  // 订单id
	OrderNo              string  `gorm:"column:order_no;not null;comment:订单编号" json:"order_no"`                                                  // 订单编号
	SiteID               int32   `gorm:"column:site_id;not null;comment:商家id" json:"site_id"`                                                    // 商家id
	MemberID             int32   `gorm:"column:member_id;not null;comment:购买会员id" json:"member_id"`                                              // 购买会员id
	GoodsID              int32   `gorm:"column:goods_id;not null;comment:商品id" json:"goods_id"`                                                  // 商品id
	SkuID                int32   `gorm:"column:sku_id;not null;comment:商品skuid" json:"sku_id"`                                                   // 商品skuid
	SkuName              string  `gorm:"column:sku_name;not null;comment:商品名称" json:"sku_name"`                                                  // 商品名称
	SkuImage             string  `gorm:"column:sku_image;not null;comment:商品图片" json:"sku_image"`                                                // 商品图片
	SkuNo                string  `gorm:"column:sku_no;not null;comment:商品编码" json:"sku_no"`                                                      // 商品编码
	IsVirtual            int32   `gorm:"column:is_virtual;not null;comment:是否是虚拟商品" json:"is_virtual"`                                           // 是否是虚拟商品
	GoodsClass           int32   `gorm:"column:goods_class;not null;comment:商品种类(1.实物 2.虚拟3.卡券)" json:"goods_class"`                             // 商品种类(1.实物 2.虚拟3.卡券)
	GoodsClassName       string  `gorm:"column:goods_class_name;not null;comment:商品类型名称" json:"goods_class_name"`                                // 商品类型名称
	Price                float64 `gorm:"column:price;not null;default:0.00;comment:商品卖价" json:"price"`                                           // 商品卖价
	CostPrice            float64 `gorm:"column:cost_price;not null;default:0.00;comment:成本价" json:"cost_price"`                                  // 成本价
	Num                  int32   `gorm:"column:num;not null;comment:购买数量" json:"num"`                                                            // 购买数量
	GoodsMoney           float64 `gorm:"column:goods_money;not null;default:0.00;comment:商品总价" json:"goods_money"`                               // 商品总价
	CostMoney            float64 `gorm:"column:cost_money;not null;default:0.00;comment:成本总价" json:"cost_money"`                                 // 成本总价
	DeliveryStatus       int32   `gorm:"column:delivery_status;not null;comment:配送状态" json:"delivery_status"`                                    // 配送状态
	DeliveryNo           string  `gorm:"column:delivery_no;not null;comment:配送单号" json:"delivery_no"`                                            // 配送单号
	GiftFlag             int32   `gorm:"column:gift_flag;not null;comment:赠品标识" json:"gift_flag"`                                                // 赠品标识
	RefundNo             string  `gorm:"column:refund_no;not null;comment:退款编号（申请产生）" json:"refund_no"`                                          // 退款编号（申请产生）
	RefundStatus         int32   `gorm:"column:refund_status;not null;comment:退款状态 0：正常状态；1退款申请中；2待转账：3；退款已完成" json:"refund_status"`             // 退款状态 0：正常状态；1退款申请中；2待转账：3；退款已完成
	RefundStatusName     string  `gorm:"column:refund_status_name;not null;comment:退款状态名称" json:"refund_status_name"`                            // 退款状态名称
	RefundStatusAction   string  `gorm:"column:refund_status_action;not null;comment:退款操作" json:"refund_status_action"`                          // 退款操作
	RefundType           int32   `gorm:"column:refund_type;not null;comment:退款方式" json:"refund_type"`                                            // 退款方式
	RefundApplyMoney     float64 `gorm:"column:refund_apply_money;not null;default:0.00;comment:退款申请金额" json:"refund_apply_money"`               // 退款申请金额
	RefundReason         string  `gorm:"column:refund_reason;not null;comment:退款原因" json:"refund_reason"`                                        // 退款原因
	RefundRealMoney      float64 `gorm:"column:refund_real_money;not null;default:0.00;comment:实际退款金额" json:"refund_real_money"`                 // 实际退款金额
	RefundDeliveryName   string  `gorm:"column:refund_delivery_name;not null;comment:退款公司名称" json:"refund_delivery_name"`                        // 退款公司名称
	RefundDeliveryNo     string  `gorm:"column:refund_delivery_no;not null;comment:退款单号" json:"refund_delivery_no"`                              // 退款单号
	RefundTime           int32   `gorm:"column:refund_time;not null;comment:实际退款时间" json:"refund_time"`                                          // 实际退款时间
	RefundRefuseReason   string  `gorm:"column:refund_refuse_reason;not null;comment:退款拒绝原因" json:"refund_refuse_reason"`                        // 退款拒绝原因
	RefundActionTime     int32   `gorm:"column:refund_action_time;not null;comment:退款时间" json:"refund_action_time"`                              // 退款时间
	DeliveryStatusName   string  `gorm:"column:delivery_status_name;not null;comment:配送状态名称" json:"delivery_status_name"`                        // 配送状态名称
	RealGoodsMoney       float64 `gorm:"column:real_goods_money;not null;default:0.00;comment:实际商品购买价" json:"real_goods_money"`                  // 实际商品购买价
	RefundRemark         string  `gorm:"column:refund_remark;not null;comment:退款说明" json:"refund_remark"`                                        // 退款说明
	RefundDeliveryRemark string  `gorm:"column:refund_delivery_remark;not null;comment:买家退货说明" json:"refund_delivery_remark"`                    // 买家退货说明
	RefundAddress        string  `gorm:"column:refund_address;not null;comment:退货地址" json:"refund_address"`                                      // 退货地址
	RefundExpressNum     string  `gorm:"column:refund_express_num;not null;comment:退款单号" json:"refund_express_num"`                              // 退款单号
	IsRefundStock        int32   `gorm:"column:is_refund_stock;not null;comment:是否返还库存" json:"is_refund_stock"`                                  // 是否返还库存
	RefundMoneyType      int32   `gorm:"column:refund_money_type;not null;default:1;comment:退款方式   1 原路退款 2线下退款3退款到余额" json:"refund_money_type"` // 退款方式   1 原路退款 2线下退款3退款到余额
	ShopActiveRefund     bool    `gorm:"column:shop_active_refund;not null;comment:商家主动退款（0否  1是）" json:"shop_active_refund"`                    // 商家主动退款（0否  1是）
	ShopRefundRemark     string  `gorm:"column:shop_refund_remark;not null;comment:商家退款说明" json:"shop_refund_remark"`                            // 商家退款说明
	RefundMode           int32   `gorm:"column:refund_mode;not null;default:1;comment:退款类型 1退款 2售后" json:"refund_mode"`                          // 退款类型 1退款 2售后
	PromotionMoney       float64 `gorm:"column:promotion_money;not null;default:0.00;comment:优惠金额" json:"promotion_money"`                       // 优惠金额
	CouponMoney          float64 `gorm:"column:coupon_money;not null;default:0.00;comment:优惠券金额" json:"coupon_money"`                            // 优惠券金额
	AdjustMoney          float64 `gorm:"column:adjust_money;not null;default:0.00;comment:调整金额" json:"adjust_money"`                             // 调整金额
	GoodsName            string  `gorm:"column:goods_name;not null;comment:商品名称" json:"goods_name"`                                              // 商品名称
	SkuSpecFormat        string  `gorm:"column:sku_spec_format;not null;comment:sku规格格式" json:"sku_spec_format"`                                 // sku规格格式
	IsFenxiao            int32   `gorm:"column:is_fenxiao;not null;default:1" json:"is_fenxiao"`
	UsePoint             int32   `gorm:"column:use_point;not null;comment:积分抵扣所用积分数" json:"use_point"`               // 积分抵扣所用积分数
	PointMoney           float64 `gorm:"column:point_money;not null;default:0.00;comment:积分抵扣金额" json:"point_money"` // 积分抵扣金额
	RefundDeliveryMoney  float64 `gorm:"column:refund_delivery_money;not null;default:0.00" json:"refund_delivery_money"`
	CreateTime           uint    `gorm:"column:create_time;not null;autoCreateTime" json:"create_time"`
	IsGetFree            int32   `gorm:"column:is_get_free;comment:0:不是换购；1：是换购" json:"is_get_free"`                                      // 0:不是换购；1：是换购
	GetfreeOrderGoodsPid int32   `gorm:"column:getfree_order_goods_pid;not null;comment:换购副商品独有，指定主商品订单项" json:"getfree_order_goods_pid"` // 换购副商品独有，指定主商品订单项
	DiscountGoodsID      int32   `gorm:"column:discount_goods_id;comment:参加限时折扣的优惠商品id" json:"discount_goods_id"`                         // 参加限时折扣的优惠商品id
	DiscountGoodsLimit   int32   `gorm:"column:discount_goods_limit;comment:商品限购数量" json:"discount_goods_limit"`                          // 商品限购数量
	OriginalPrice        float64 `gorm:"column:original_price;comment:商品原价" json:"original_price"`                                        // 商品原价
	IsChineseMedicine    int32   `gorm:"column:is_chinese_medicine;comment:是否是中药商品 0 不是 1是" json:"is_chinese_medicine"`                   // 是否是中药商品 0 不是 1是
	DiscountMoney        float64 `gorm:"column:discount_money;not null;default:0.00;comment:折扣、秒杀优惠金额" json:"discount_money"`             // 折扣、秒杀优惠金额
	GoodsAttr            string  `gorm:"column:goods_attr;not null;comment:商品属性" json:"goods_attr"`                                       // 商品属性
	IssueNum             int32   `gorm:"column:issue_num;not null;comment:实际发货数量（ERP）" json:"issue_num"`                                  // 实际发货数量（ERP）
	SeckillID            int32   `gorm:"column:seckill_id;not null;comment:秒杀id" json:"seckill_id"`                                       // 秒杀id
	TaxRate              float64 `gorm:"column:tax_rate;not null;default:0.00;comment:税率" json:"tax_rate"`                                // 税率
	SalesmanMemberID     int32   `gorm:"column:salesman_member_id;not null;comment:代客下单业务员id，非代客下单为0（新）" json:"salesman_member_id"`       // 代客下单业务员id，非代客下单为0（新）
	OldOrderGoodsID      int32   `gorm:"column:old_order_goods_id;not null;comment:部分退款旧order_goods_id" json:"old_order_goods_id"`        // 部分退款旧order_goods_id
	PromotionLabel       string  `gorm:"column:promotion_label;comment:活动标识" json:"promotion_label"`                                      // 活动标识
	RefundNum            int32   `gorm:"column:refund_num;not null;comment:退款数量" json:"refund_num"`                                       // 退款数量
	Goods                Goods   `gorm:"foreignKey:goods_id;references:goods_id" json:"goods"`
}

// MarshalBinary 支持json序列化
func (m *OrderGoods) MarshalBinary() (data []byte, err error) {
	return json.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *OrderGoods) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

// TableName OrderGoods's table name
func (*OrderGoods) TableName() string {
	return TableNameOrderGoods
}
