// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"encoding/json"
)

const TableNameConfig = "ydd_config"

// Config 系统配置表
type Config struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`               // 主键
	SiteID     int32  `gorm:"column:site_id;not null;comment:站点id（店铺，分站）,总平台端为0" json:"site_id"`          // 站点id（店铺，分站）,总平台端为0
	AppModule  string `gorm:"column:app_module;not null;comment:应用端口关键字" json:"app_module"`               // 应用端口关键字
	ConfigKey  string `gorm:"column:config_key;not null;comment:配置项关键字" json:"config_key"`                // 配置项关键字
	Value      string `gorm:"column:value;not null;comment:配置值json" json:"value"`                         // 配置值json
	ConfigDesc string `gorm:"column:config_desc;not null;comment:描述" json:"config_desc"`                  // 描述
	IsUse      int32  `gorm:"column:is_use;not null;default:1;comment:是否启用 1启用 0不启用" json:"is_use"`       // 是否启用 1启用 0不启用
	CreateTime uint   `gorm:"column:create_time;not null;autoCreateTime;comment:创建时间" json:"create_time"` // 创建时间
	ModifyTime int32  `gorm:"column:modify_time;not null;comment:修改时间" json:"modify_time"`                // 修改时间
}

// MarshalBinary 支持json序列化
func (m *Config) MarshalBinary() (data []byte, err error) {
	return json.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *Config) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

// TableName Config's table name
func (*Config) TableName() string {
	return TableNameConfig
}
