// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"encoding/json"
)

const TableNameOrderSettlementType = "ydd_order_settlement_type"

// OrderSettlementType 订单结算方式
type OrderSettlementType struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string `gorm:"column:name;not null;comment:支付方式名称" json:"name"`                    // 支付方式名称
	IsPay     bool   `gorm:"column:is_pay;not null;default:1;comment:是否调起支付" json:"is_pay"`      // 是否调起支付
	IsAutoPay bool   `gorm:"column:is_auto_pay;not null;comment:提交订单时是否自动支付" json:"is_auto_pay"` // 提交订单时是否自动支付
	Remark    string `gorm:"column:remark;not null;comment:备注" json:"remark"`                    // 备注
	Sort      int32  `gorm:"column:sort;not null;comment:排序 ASC" json:"sort"`                    // 排序 ASC
	Status    int32  `gorm:"column:status;not null;default:1;comment:状态" json:"status"`          // 状态
	JSONData  string `gorm:"column:json_data;not null;comment:配置信息" json:"json_data"`            // 配置信息
	Type      int32  `gorm:"column:type;not null;comment:0无 1公对公资料 2=资信下单" json:"type"`          // 0无 1公对公资料 2=资信下单
}

// MarshalBinary 支持json序列化
func (m *OrderSettlementType) MarshalBinary() (data []byte, err error) {
	return json.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *OrderSettlementType) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

// TableName OrderSettlementType's table name
func (*OrderSettlementType) TableName() string {
	return TableNameOrderSettlementType
}
