// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"encoding/json"
	"time"
)

const TableNameOrder = "ydd_order"

// Order 订单表
type Order struct {
	OrderID              int32               `gorm:"column:order_id;primaryKey;autoIncrement:true" json:"order_id"`
	OrderNo              string              `gorm:"column:order_no;not null;comment:订单编号" json:"order_no"`                                                         // 订单编号
	SiteID               int32               `gorm:"column:site_id;not null;comment:商家id" json:"site_id"`                                                           // 商家id
	SiteName             string              `gorm:"column:site_name;not null;comment:店铺名称" json:"site_name"`                                                       // 店铺名称
	WebsiteID            int32               `gorm:"column:website_id;not null;comment:分站id" json:"website_id"`                                                     // 分站id
	OrderName            string              `gorm:"column:order_name;not null;comment:订单内容" json:"order_name"`                                                     // 订单内容
	OrderFrom            string              `gorm:"column:order_from;not null;comment:订单来源" json:"order_from"`                                                     // 订单来源
	OrderFromName        string              `gorm:"column:order_from_name;not null;comment:订单来源名称" json:"order_from_name"`                                         // 订单来源名称
	OrderType            int32               `gorm:"column:order_type;not null;comment:订单类型 1. 普通订单  2. 门店订单  3. 本地配送订单4. 虚拟订单" json:"order_type"`                  // 订单类型 1. 普通订单  2. 门店订单  3. 本地配送订单4. 虚拟订单
	OrderTypeName        string              `gorm:"column:order_type_name;not null;comment:订单类型名称" json:"order_type_name"`                                         // 订单类型名称
	OrderPromotionType   int32               `gorm:"column:order_promotion_type;not null;comment:订单营销类型" json:"order_promotion_type"`                               // 订单营销类型
	OrderPromotionName   string              `gorm:"column:order_promotion_name;not null;comment:营销活动类型名称" json:"order_promotion_name"`                             // 营销活动类型名称
	PromotionID          int32               `gorm:"column:promotion_id;not null;comment:营销活动id" json:"promotion_id"`                                               // 营销活动id
	OutTradeNo           string              `gorm:"column:out_trade_no;not null;comment:支付流水号" json:"out_trade_no"`                                                // 支付流水号
	OutTradeNo2          string              `gorm:"column:out_trade_no_2;not null;comment:支付流水号（多次支付）" json:"out_trade_no_2"`                                      // 支付流水号（多次支付）
	DeliveryCode         string              `gorm:"column:delivery_code;not null;comment:整体提货编码" json:"delivery_code"`                                             // 整体提货编码
	OrderStatus          int32               `gorm:"column:order_status;not null;comment:订单状态 0：待支付；1待发货；3已发货；4已收货；10已完成；-1已关闭  refunding：退款中" json:"order_status"` // 订单状态 0：待支付；1待发货；3已发货；4已收货；10已完成；-1已关闭  refunding：退款中
	OrderStatusName      string              `gorm:"column:order_status_name;not null;comment:订单状态名称" json:"order_status_name"`                                     // 订单状态名称
	OrderStatusAction    string              `gorm:"column:order_status_action;not null;comment:订单操作" json:"order_status_action"`                                   // 订单操作
	PayStatus            int32               `gorm:"column:pay_status;not null;comment:支付状态" json:"pay_status"`                                                     // 支付状态
	DeliveryStatus       int32               `gorm:"column:delivery_status;not null;comment:配送状态" json:"delivery_status"`                                           // 配送状态
	RefundStatus         int32               `gorm:"column:refund_status;not null;comment:退款状态" json:"refund_status"`                                               // 退款状态
	PayType              string              `gorm:"column:pay_type;not null;comment:支付方式" json:"pay_type"`                                                         // 支付方式
	PayTypeName          string              `gorm:"column:pay_type_name;not null;comment:支付类型名称" json:"pay_type_name"`                                             // 支付类型名称
	DeliveryType         string              `gorm:"column:delivery_type;not null;default:0;comment:配送方式" json:"delivery_type"`                                     // 配送方式
	DeliveryTypeName     string              `gorm:"column:delivery_type_name;not null;comment:配送方式名称" json:"delivery_type_name"`                                   // 配送方式名称
	MemberID             int32               `gorm:"column:member_id;not null;comment:购买人uid" json:"member_id"`                                                     // 购买人uid
	Name                 string              `gorm:"column:name;not null;comment:购买人姓名" json:"name"`                                                                // 购买人姓名
	Mobile               string              `gorm:"column:mobile;not null;comment:购买人手机" json:"mobile"`                                                            // 购买人手机
	Telephone            string              `gorm:"column:telephone;not null;comment:购买人固定电话" json:"telephone"`                                                    // 购买人固定电话
	ProvinceID           int32               `gorm:"column:province_id;not null;comment:购买人省id" json:"province_id"`                                                 // 购买人省id
	CityID               int32               `gorm:"column:city_id;not null;comment:购买人市id" json:"city_id"`                                                         // 购买人市id
	DistrictID           int32               `gorm:"column:district_id;not null;comment:购买人区县id" json:"district_id"`                                                // 购买人区县id
	CommunityID          int32               `gorm:"column:community_id;not null;comment:购买人社区id" json:"community_id"`                                              // 购买人社区id
	Address              string              `gorm:"column:address;not null;comment:购买人地址" json:"address"`                                                          // 购买人地址
	FullAddress          string              `gorm:"column:full_address;not null;comment:购买人详细地址" json:"full_address"`                                              // 购买人详细地址
	Longitude            string              `gorm:"column:longitude;not null;comment:购买人地址经度" json:"longitude"`                                                    // 购买人地址经度
	Latitude             string              `gorm:"column:latitude;not null;comment:购买人地址纬度" json:"latitude"`                                                      // 购买人地址纬度
	BuyerIP              string              `gorm:"column:buyer_ip;not null;comment:购买人ip" json:"buyer_ip"`                                                        // 购买人ip
	BuyerAskDeliveryTime int32               `gorm:"column:buyer_ask_delivery_time;not null;comment:购买人要求配送时间" json:"buyer_ask_delivery_time"`                      // 购买人要求配送时间
	BuyerMessage         string              `gorm:"column:buyer_message;not null;comment:购买人留言信息" json:"buyer_message"`                                            // 购买人留言信息
	GoodsMoney           float64             `gorm:"column:goods_money;not null;default:0.00;comment:商品总金额" json:"goods_money"`                                     // 商品总金额
	DeliveryMoney        float64             `gorm:"column:delivery_money;not null;default:0.00;comment:配送费用" json:"delivery_money"`                                // 配送费用
	PromotionMoney       float64             `gorm:"column:promotion_money;not null;default:0.00;comment:订单优惠金额（满减）" json:"promotion_money"`                        // 订单优惠金额（满减）
	CouponID             int32               `gorm:"column:coupon_id;not null;comment:优惠券id" json:"coupon_id"`                                                      // 优惠券id
	CouponMoney          float64             `gorm:"column:coupon_money;not null;default:0.00;comment:优惠券金额" json:"coupon_money"`                                   // 优惠券金额
	InvoiceMoney         float64             `gorm:"column:invoice_money;not null;default:0.00;comment:发票金额" json:"invoice_money"`                                  // 发票金额
	OrderMoney           float64             `gorm:"column:order_money;not null;default:0.00;comment:订单合计金额" json:"order_money"`                                    // 订单合计金额
	AdjustMoney          float64             `gorm:"column:adjust_money;not null;default:0.00;comment:订单调整金额" json:"adjust_money"`                                  // 订单调整金额
	BalanceMoney         float64             `gorm:"column:balance_money;not null;default:0.00;comment:余额支付金额" json:"balance_money"`                                // 余额支付金额
	PayMoney             float64             `gorm:"column:pay_money;not null;default:0.00;comment:抵扣之后应付金额" json:"pay_money"`                                      // 抵扣之后应付金额
	CreateTime           uint                `gorm:"column:create_time;not null;autoCreateTime;comment:创建时间" json:"create_time"`                                    // 创建时间
	PayTime              int32               `gorm:"column:pay_time;not null;comment:订单支付时间" json:"pay_time"`                                                       // 订单支付时间
	DeliveryTime         int32               `gorm:"column:delivery_time;not null;comment:订单配送时间" json:"delivery_time"`                                             // 订单配送时间
	SignTime             int32               `gorm:"column:sign_time;not null;comment:订单签收时间" json:"sign_time"`                                                     // 订单签收时间
	FinishTime           int32               `gorm:"column:finish_time;not null;comment:订单完成时间" json:"finish_time"`                                                 // 订单完成时间
	CloseTime            int32               `gorm:"column:close_time;not null;comment:订单关闭时间" json:"close_time"`                                                   // 订单关闭时间
	IsLock               int32               `gorm:"column:is_lock;not null;comment:是否锁定订单（针对维权，锁定不可操作）" json:"is_lock"`                                            // 是否锁定订单（针对维权，锁定不可操作）
	IsEvaluate           int32               `gorm:"column:is_evaluate;not null;comment:是否允许订单评价" json:"is_evaluate"`                                               // 是否允许订单评价
	IsDelete             int32               `gorm:"column:is_delete;not null;comment:是否删除(针对后台)" json:"is_delete"`                                                 // 是否删除(针对后台)
	IsEnableRefund       int32               `gorm:"column:is_enable_refund;not null;comment:是否允许退款" json:"is_enable_refund"`                                       // 是否允许退款
	Remark               string              `gorm:"column:remark;not null;comment:卖家留言" json:"remark"`                                                             // 卖家留言
	GoodsNum             int32               `gorm:"column:goods_num;not null;comment:商品件数" json:"goods_num"`                                                       // 商品件数
	DeliveryStoreID      int32               `gorm:"column:delivery_store_id;not null;comment:门店id" json:"delivery_store_id"`                                       // 门店id
	DeliveryStatusName   string              `gorm:"column:delivery_status_name;not null;comment:发货状态" json:"delivery_status_name"`                                 // 发货状态
	IsSettlement         bool                `gorm:"column:is_settlement;not null;comment:是否进行结算" json:"is_settlement"`                                             // 是否进行结算
	StoreSettlementID    int32               `gorm:"column:store_settlement_id;not null;comment:门店结算id" json:"store_settlement_id"`                                 // 门店结算id
	DeliveryStoreName    string              `gorm:"column:delivery_store_name;not null;comment:门店名称" json:"delivery_store_name"`                                   // 门店名称
	PromotionType        string              `gorm:"column:promotion_type;not null;comment:营销类型" json:"promotion_type"`                                             // 营销类型
	PromotionTypeName    string              `gorm:"column:promotion_type_name;not null;comment:营销类型名称" json:"promotion_type_name"`                                 // 营销类型名称
	PromotionStatusName  string              `gorm:"column:promotion_status_name;not null;comment:营销状态名称" json:"promotion_status_name"`                             // 营销状态名称
	DeliveryStoreInfo    string              `gorm:"column:delivery_store_info;comment:门店信息(json)" json:"delivery_store_info"`                                      // 门店信息(json)
	VirtualCode          string              `gorm:"column:virtual_code;not null;comment:虚拟商品码" json:"virtual_code"`                                                // 虚拟商品码
	EvaluateStatus       int32               `gorm:"column:evaluate_status;not null;comment:评价状态，0：未评价，1：已评价，2：已追评" json:"evaluate_status"`                         // 评价状态，0：未评价，1：已评价，2：已追评
	EvaluateStatusName   string              `gorm:"column:evaluate_status_name;not null;comment:评价状态名称，未评价，已评价，已追评" json:"evaluate_status_name"`                   // 评价状态名称，未评价，已评价，已追评
	RefundMoney          float64             `gorm:"column:refund_money;not null;default:0.00;comment:订单退款金额" json:"refund_money"`                                  // 订单退款金额
	Commission           float64             `gorm:"column:commission;not null;default:0.00;comment:总支出佣金" json:"commission"`                                       // 总支出佣金
	IsInvoice            int32               `gorm:"column:is_invoice;not null;comment:是否需要发票 0 无发票  1 有发票" json:"is_invoice"`                                      // 是否需要发票 0 无发票  1 有发票
	InvoiceType          int32               `gorm:"column:invoice_type;not null;default:1;comment:发票类型  1 纸质发票 2 电子发票" json:"invoice_type"`                        // 发票类型  1 纸质发票 2 电子发票
	InvoiceTitle         string              `gorm:"column:invoice_title;not null;comment:发票抬头" json:"invoice_title"`                                               // 发票抬头
	TaxpayerNumber       string              `gorm:"column:taxpayer_number;not null;comment:纳税人识别号" json:"taxpayer_number"`                                         // 纳税人识别号
	InvoiceRate          float64             `gorm:"column:invoice_rate;not null;default:0.00;comment:发票税率" json:"invoice_rate"`                                    // 发票税率
	InvoiceContent       string              `gorm:"column:invoice_content;not null;comment:发票内容" json:"invoice_content"`                                           // 发票内容
	InvoiceDeliveryMoney float64             `gorm:"column:invoice_delivery_money;not null;default:0.00;comment:发票邮寄费用" json:"invoice_delivery_money"`              // 发票邮寄费用
	InvoiceFullAddress   string              `gorm:"column:invoice_full_address;not null;comment:发票邮寄地址" json:"invoice_full_address"`                               // 发票邮寄地址
	IsTaxInvoice         int32               `gorm:"column:is_tax_invoice;not null;comment:是否需要增值税专用发票" json:"is_tax_invoice"`                                      // 是否需要增值税专用发票
	InvoiceEmail         string              `gorm:"column:invoice_email;not null;comment:发票发送邮件" json:"invoice_email"`                                             // 发票发送邮件
	InvoiceTitleType     int32               `gorm:"column:invoice_title_type;not null;comment:发票抬头类型  1 个人  2 企业" json:"invoice_title_type"`                       // 发票抬头类型  1 个人  2 企业
	IsFenxiao            int32               `gorm:"column:is_fenxiao;not null;default:1;comment:是否参与分销 0不参与 1参与" json:"is_fenxiao"`                                // 是否参与分销 0不参与 1参与
	PointMoney           float64             `gorm:"column:point_money;not null;default:0.00;comment:积分抵现金额" json:"point_money"`                                    // 积分抵现金额
	MemberCardMoney      float64             `gorm:"column:member_card_money;not null;default:0.00;comment:会员卡订单金额" json:"member_card_money"`                       // 会员卡订单金额
	MemberCardOrder      int32               `gorm:"column:member_card_order;not null;comment:会员卡订单id" json:"member_card_order"`                                    // 会员卡订单id
	InvoiceStatus        bool                `gorm:"column:invoice_status;not null;comment:发票状态（0待开票   1已开票）" json:"invoice_status"`                                // 发票状态（0待开票   1已开票）
	InvoiceRemark        string              `gorm:"column:invoice_remark;comment:发票备注" json:"invoice_remark"`                                                      // 发票备注
	InvoiceCode          string              `gorm:"column:invoice_code;not null;comment:发票编码" json:"invoice_code"`                                                 // 发票编码
	InvoiceImage         string              `gorm:"column:invoice_image;not null;comment:发票凭证" json:"invoice_image"`                                               // 发票凭证
	InvoiceTime          int32               `gorm:"column:invoice_time;not null;comment:开票时间" json:"invoice_time"`                                                 // 开票时间
	PredictDeliveryTime  int32               `gorm:"column:predict_delivery_time;not null;comment:预计发货时间" json:"predict_delivery_time"`                             // 预计发货时间
	IsVideoNumber        int32               `gorm:"column:is_video_number;not null;comment:订单是否同步到视频号" json:"is_video_number"`                                     // 订单是否同步到视频号
	SyncTime             int32               `gorm:"column:sync_time;not null;comment:同步到ERP时间" json:"sync_time"`                                                   // 同步到ERP时间
	IsGetfreeOrder       int32               `gorm:"column:is_getfree_order;comment:是否存在换购商品 0 不存在换购，1存在换购商品" json:"is_getfree_order"`                              // 是否存在换购商品 0 不存在换购，1存在换购商品
	IsDiscountOrder      int32               `gorm:"column:is_discount_order;comment:是否存在特价商品 0 不存在特价，1存在特价商品" json:"is_discount_order"`                            // 是否存在特价商品 0 不存在特价，1存在特价商品
	IsChineseMedicine    int32               `gorm:"column:is_chinese_medicine;comment:是否是中药商品 0 不是 1是" json:"is_chinese_medicine"`                                 // 是否是中药商品 0 不是 1是
	IsSaleControl        int32               `gorm:"column:is_sale_control;comment:是否是控销订单" json:"is_sale_control"`                                                 // 是否是控销订单
	FenxiaoMemberID      int32               `gorm:"column:fenxiao_member_id;not null;comment:代客下单业务员id，非代客下单为0" json:"fenxiao_member_id"`                          // 代客下单业务员id，非代客下单为0
	SettleTypeID         int32               `gorm:"column:settle_type_id;not null;default:1;comment:结算类型ID" json:"settle_type_id"`                                 // 结算类型ID
	DiscountMoney        float64             `gorm:"column:discount_money;not null;default:0.00;comment:折扣、秒杀优惠金额" json:"discount_money"`                           // 折扣、秒杀优惠金额
	AgentPayOpenid       string              `gorm:"column:agent_pay_openid;not null;comment:代支付人微信openid" json:"agent_pay_openid"`                                 // 代支付人微信openid
	ReceiptType          int32               `gorm:"column:receipt_type;not null;default:1;comment:1 无 2 普票 3 专票" json:"receipt_type"`                              // 1 无 2 普票 3 专票
	Employeename         string              `gorm:"column:employeename;not null;comment:开票人" json:"employeename"`                                                  // 开票人
	Employeecode         string              `gorm:"column:employeecode;not null;comment:开票人code" json:"employeecode"`                                              // 开票人code
	SalesmanMemberID     int32               `gorm:"column:salesman_member_id;not null;comment:代客下单业务员id，非代客下单为0（新）" json:"salesman_member_id"`                     // 代客下单业务员id，非代客下单为0（新）
	VoucherImg           string              `gorm:"column:voucher_img;comment:凭证" json:"voucher_img"`                                                              // 凭证
	YcSyncTime           time.Time           `gorm:"column:yc_sync_time;comment:云仓同步时间" json:"yc_sync_time"`                                                        // 云仓同步时间
	OrderGoods           []OrderGoods        `gorm:"foreignKey:order_id;references:order_id" json:"order_goods"`
	StaffSalesman        StaffSalesman       `gorm:"foreignKey:member_id;references:salesman_member_id" json:"staff_salesman"`
	SettlementType       OrderSettlementType `gorm:"foreignKey:ID;references:settle_type_id" json:"settlement_type"`
}

// MarshalBinary 支持json序列化
func (m *Order) MarshalBinary() (data []byte, err error) {
	return json.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *Order) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
