// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package shop_model

import (
	"encoding/json"
)

const TableNameStaffSalesman = "ydd_staff_salesman"

// StaffSalesman 员工-业务员表
type StaffSalesman struct {
	SalesmanID      int32  `gorm:"column:salesman_id;primaryKey;autoIncrement:true;comment:业务员id" json:"salesman_id"` // 业务员id
	Pid             int32  `gorm:"column:pid;not null;comment:上级id" json:"pid"`                                       // 上级id
	MemberID        int32  `gorm:"column:member_id;not null;comment:在用户表的id" json:"member_id"`                        // 在用户表的id
	FirstID         int32  `gorm:"column:first_id;not null;comment:一级区域id" json:"first_id"`                           // 一级区域id
	SecondID        int32  `gorm:"column:second_id;not null;comment:二级区域id" json:"second_id"`                         // 二级区域id
	RegionID        int32  `gorm:"column:region_id;not null;comment:三级区域id" json:"region_id"`                         // 三级区域id
	SalesmanName    string `gorm:"column:salesman_name;not null;comment:业务员名称" json:"salesman_name"`                  // 业务员名称
	SalesmanMobile  string `gorm:"column:salesman_mobile;not null;comment:手机号" json:"salesman_mobile"`                // 手机号
	SalesmanAccount string `gorm:"column:salesman_account;not null;comment:登录账号" json:"salesman_account"`             // 登录账号
	Level           int32  `gorm:"column:level;not null;default:1;comment:区域级别 1一级 2二级 3三级" json:"level"`             // 区域级别 1一级 2二级 3三级
	ErpUID          string `gorm:"column:erp_uid;not null;comment:ERP中的ID" json:"erp_uid"`                            // ERP中的ID
	ErpSaleerID     string `gorm:"column:erp_saleer_id;not null;comment:ERP中的销售id" json:"erp_saleer_id"`              // ERP中的销售id
	Status          int32  `gorm:"column:status;not null;default:1;comment:状态" json:"status"`                         // 状态
	AccountType     int32  `gorm:"column:account_type;not null;comment:账户类型 0-业务员  1-全国代理" json:"account_type"`       // 账户类型 0-业务员  1-全国代理
	Remarks         string `gorm:"column:remarks;comment:简介" json:"remarks"`                                          // 简介
	CreatedAt       int32  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                         // 创建时间
	UpdatedAt       int32  `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt       int32  `gorm:"column:deleted_at" json:"deleted_at"`
}

// MarshalBinary 支持json序列化
func (m *StaffSalesman) MarshalBinary() (data []byte, err error) {
	return json.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *StaffSalesman) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

// TableName StaffSalesman's table name
func (*StaffSalesman) TableName() string {
	return TableNameStaffSalesman
}
