// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package shop_model

import (
	"encoding/json"
)

const TableNameMemberBusinessScopeRow = "ydd_member_business_scope_row"

// MemberBusinessScopeRow mapped from table <ydd_member_business_scope_row>
type MemberBusinessScopeRow struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name   string `gorm:"column:name" json:"name"`
	TypeID string `gorm:"column:type_id" json:"type_id"`
}

// MarshalBinary 支持json序列化
func (m *MemberBusinessScopeRow) MarshalBinary() (data []byte, err error) {
	return json.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *MemberBusinessScopeRow) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

// TableName MemberBusinessScopeRow's table name
func (*MemberBusinessScopeRow) TableName() string {
	return TableNameMemberBusinessScopeRow
}
