// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package shop_model

import (
	"encoding/json"
)

const TableNameArea = "ydd_area"

// Area 地址表
type Area struct {
	ID        int32  `gorm:"column:id;primaryKey" json:"id"`
	Pid       int32  `gorm:"column:pid;not null;comment:父级" json:"pid"`                    // 父级
	Name      string `gorm:"column:name;not null;comment:名称" json:"name"`                  // 名称
	Shortname string `gorm:"column:shortname;not null;comment:简称" json:"shortname"`        // 简称
	Longitude string `gorm:"column:longitude;not null;comment:经度" json:"longitude"`        // 经度
	Latitude  string `gorm:"column:latitude;not null;comment:纬度" json:"latitude"`          // 纬度
	Level     int32  `gorm:"column:level;not null;comment:级别" json:"level"`                // 级别
	Sort      int32  `gorm:"column:sort;not null;comment:排序" json:"sort"`                  // 排序
	Status    bool   `gorm:"column:status;not null;default:1;comment:状态1有效" json:"status"` // 状态1有效
	IsBlack   int32  `gorm:"column:is_black;not null;comment:是否黑名单" json:"is_black"`       // 是否黑名单
}

// MarshalBinary 支持json序列化
func (m *Area) MarshalBinary() (data []byte, err error) {
	return json.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *Area) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

// TableName Area's table name
func (*Area) TableName() string {
	return TableNameArea
}
