// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package shop_model

import (
	"encoding/json"
)

const TableNameMemberLabel = "ydd_member_label"

// MemberLabel 会员标签
type MemberLabel struct {
	LabelID              int32  `gorm:"column:label_id;primaryKey;autoIncrement:true;comment:标签id" json:"label_id"`                                                           // 标签id
	SiteID               int32  `gorm:"column:site_id;not null;comment:site_id" json:"site_id"`                                                                               // site_id
	LabelName            string `gorm:"column:label_name;not null;comment:标签名称" json:"label_name"`                                                                            // 标签名称
	CreateTime           uint   `gorm:"column:create_time;not null;autoCreateTime;comment:创建时间" json:"create_time"`                                                           // 创建时间
	ModifyTime           int32  `gorm:"column:modify_time;not null;comment:修改时间" json:"modify_time"`                                                                          // 修改时间
	Remark               string `gorm:"column:remark;not null;comment:备注" json:"remark"`                                                                                      // 备注
	Sort                 int32  `gorm:"column:sort;not null;comment:排序" json:"sort"`                                                                                          // 排序
	QualificationsConfig string `gorm:"column:qualifications_config;not null;default:[];comment:资质配置 [{'id':1,'is_must':1}]  is_must是否必须 1是 0否" json:"qualifications_config"` // 资质配置 [{'id':1,'is_must':1}]  is_must是否必须 1是 0否
}

// MarshalBinary 支持json序列化
func (m *MemberLabel) MarshalBinary() (data []byte, err error) {
	return json.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *MemberLabel) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

// TableName MemberLabel's table name
func (*MemberLabel) TableName() string {
	return TableNameMemberLabel
}
