// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package shop_model

import (
	"encoding/json"
	"time"
)

const TableNameErpOrderOutbound = "ydd_erp_order_outbound"

// ErpOrderOutbound mapped from table <ydd_erp_order_outbound>
type ErpOrderOutbound struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OutboundNo       string    `gorm:"column:outbound_no;comment:出库单据编号" json:"outbound_no"`                                    // 出库单据编号
	OrderNo          string    `gorm:"column:order_no;comment:订单编号" json:"order_no"`                                            // 订单编号
	GoodsErpSpid     string    `gorm:"column:goods_erp_spid;comment:商品erpid" json:"goods_erp_spid"`                             // 商品erpid
	OutboundTime     string    `gorm:"column:outbound_time;comment:出库时间" json:"outbound_time"`                                  // 出库时间
	Validity         string    `gorm:"column:validity;comment:出库的商品效期" json:"validity"`                                         // 出库的商品效期
	OutboundNum      int32     `gorm:"column:outbound_num;comment:实际出库数量" json:"outbound_num"`                                  // 实际出库数量
	OutboundPrice    float64   `gorm:"column:outbound_price;comment:实际出库单价" json:"outbound_price"`                              // 实际出库单价
	LogisticsCompany string    `gorm:"column:logistics_company;comment:物流公司名称，需与电商后台相同，如非物流发货传"无需物流"" json:"logistics_company"` // 物流公司名称，需与电商后台相同，如非物流发货传"无需物流"
	LogisticsCode    string    `gorm:"column:logistics_code;comment:运单号，无需物流时传空字符串" json:"logistics_code"`                      // 运单号，无需物流时传空字符串
	SyncTime         time.Time `gorm:"column:sync_time;not null;comment:同步的时间" json:"sync_time"`                                // 同步的时间
}

// MarshalBinary 支持json序列化
func (m *ErpOrderOutbound) MarshalBinary() (data []byte, err error) {
	return json.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *ErpOrderOutbound) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

// TableName ErpOrderOutbound's table name
func (*ErpOrderOutbound) TableName() string {
	return TableNameErpOrderOutbound
}
