// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package shop_model

import (
	"encoding/json"
	"time"
)

const TableNameMemberQualification = "ydd_member_qualification"

// MemberQualification 会员资质
type MemberQualification struct {
	ID                  int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MemberID            int32     `gorm:"column:member_id;not null;comment:用户名" json:"member_id"`                 // 用户名
	Name                string    `gorm:"column:name;not null;comment:资质名称" json:"name"`                          // 资质名称
	Identify            string    `gorm:"column:identify;not null;comment:资质标识" json:"identify"`                  // 资质标识
	ExpirationStartDate time.Time `gorm:"column:expiration_start_date;comment:开始时间" json:"expiration_start_date"` // 开始时间
	ExpirationEndDate   time.Time `gorm:"column:expiration_end_date;comment:结束时间" json:"expiration_end_date"`     // 结束时间
	LongTerm            int32     `gorm:"column:long_term;not null;comment:是否长期有效" json:"long_term"`              // 是否长期有效
	Image               string    `gorm:"column:image;not null;comment:图片地址" json:"image"`                        // 图片地址
	Status              int32     `gorm:"column:status;not null;comment:审核状态 0 待审核 1审核通过 -1审核拒绝" json:"status"`   // 审核状态 0 待审核 1审核通过 -1审核拒绝
	CardNo              string    `gorm:"column:card_no;not null;comment:证件号" json:"card_no"`                     // 证件号
	RefuseReason        string    `gorm:"column:refuse_reason;not null;comment:拒绝原因" json:"refuse_reason"`        // 拒绝原因
	Custom              string    `gorm:"column:custom;comment:自定义表单" json:"custom"`                              // 自定义表单
	VerifyData          string    `gorm:"column:verify_data;comment:核实图片（审核时上传）" json:"verify_data"`              // 核实图片（审核时上传）
}

// MarshalBinary 支持json序列化
func (m *MemberQualification) MarshalBinary() (data []byte, err error) {
	return json.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *MemberQualification) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

// TableName MemberQualification's table name
func (*MemberQualification) TableName() string {
	return TableNameMemberQualification
}
