// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package shop_query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/orm/shop_model"
)

func newArea(db *gorm.DB, opts ...gen.DOOption) area {
	_area := area{}

	_area.areaDo.UseDB(db, opts...)
	_area.areaDo.UseModel(&shop_model.Area{})

	tableName := _area.areaDo.TableName()
	_area.ALL = field.NewAsterisk(tableName)
	_area.ID = field.NewInt32(tableName, "id")
	_area.Pid = field.NewInt32(tableName, "pid")
	_area.Name = field.NewString(tableName, "name")
	_area.Shortname = field.NewString(tableName, "shortname")
	_area.Longitude = field.NewString(tableName, "longitude")
	_area.Latitude = field.NewString(tableName, "latitude")
	_area.Level = field.NewInt32(tableName, "level")
	_area.Sort = field.NewInt32(tableName, "sort")
	_area.Status = field.NewBool(tableName, "status")
	_area.IsBlack = field.NewInt32(tableName, "is_black")

	_area.fillFieldMap()

	return _area
}

// area 地址表
type area struct {
	areaDo

	ALL       field.Asterisk
	ID        field.Int32
	Pid       field.Int32  // 父级
	Name      field.String // 名称
	Shortname field.String // 简称
	Longitude field.String // 经度
	Latitude  field.String // 纬度
	Level     field.Int32  // 级别
	Sort      field.Int32  // 排序
	Status    field.Bool   // 状态1有效
	IsBlack   field.Int32  // 是否黑名单

	fieldMap map[string]field.Expr
}

func (a area) Table(newTableName string) *area {
	a.areaDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a area) As(alias string) *area {
	a.areaDo.DO = *(a.areaDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *area) updateTableName(table string) *area {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt32(table, "id")
	a.Pid = field.NewInt32(table, "pid")
	a.Name = field.NewString(table, "name")
	a.Shortname = field.NewString(table, "shortname")
	a.Longitude = field.NewString(table, "longitude")
	a.Latitude = field.NewString(table, "latitude")
	a.Level = field.NewInt32(table, "level")
	a.Sort = field.NewInt32(table, "sort")
	a.Status = field.NewBool(table, "status")
	a.IsBlack = field.NewInt32(table, "is_black")

	a.fillFieldMap()

	return a
}

func (a *area) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *area) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["pid"] = a.Pid
	a.fieldMap["name"] = a.Name
	a.fieldMap["shortname"] = a.Shortname
	a.fieldMap["longitude"] = a.Longitude
	a.fieldMap["latitude"] = a.Latitude
	a.fieldMap["level"] = a.Level
	a.fieldMap["sort"] = a.Sort
	a.fieldMap["status"] = a.Status
	a.fieldMap["is_black"] = a.IsBlack
}

func (a area) clone(db *gorm.DB) area {
	a.areaDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a area) replaceDB(db *gorm.DB) area {
	a.areaDo.ReplaceDB(db)
	return a
}

type areaDo struct{ gen.DO }

type IAreaDo interface {
	gen.SubQuery
	Debug() IAreaDo
	WithContext(ctx context.Context) IAreaDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAreaDo
	WriteDB() IAreaDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAreaDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAreaDo
	Not(conds ...gen.Condition) IAreaDo
	Or(conds ...gen.Condition) IAreaDo
	Select(conds ...field.Expr) IAreaDo
	Where(conds ...gen.Condition) IAreaDo
	Order(conds ...field.Expr) IAreaDo
	Distinct(cols ...field.Expr) IAreaDo
	Omit(cols ...field.Expr) IAreaDo
	Join(table schema.Tabler, on ...field.Expr) IAreaDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAreaDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAreaDo
	Group(cols ...field.Expr) IAreaDo
	Having(conds ...gen.Condition) IAreaDo
	Limit(limit int) IAreaDo
	Offset(offset int) IAreaDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAreaDo
	Unscoped() IAreaDo
	Create(values ...*shop_model.Area) error
	CreateInBatches(values []*shop_model.Area, batchSize int) error
	Save(values ...*shop_model.Area) error
	First() (*shop_model.Area, error)
	Take() (*shop_model.Area, error)
	Last() (*shop_model.Area, error)
	Find() ([]*shop_model.Area, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*shop_model.Area, err error)
	FindInBatches(result *[]*shop_model.Area, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*shop_model.Area) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAreaDo
	Assign(attrs ...field.AssignExpr) IAreaDo
	Joins(fields ...field.RelationField) IAreaDo
	Preload(fields ...field.RelationField) IAreaDo
	FirstOrInit() (*shop_model.Area, error)
	FirstOrCreate() (*shop_model.Area, error)
	FindByPage(offset int, limit int) (result []*shop_model.Area, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAreaDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a areaDo) Debug() IAreaDo {
	return a.withDO(a.DO.Debug())
}

func (a areaDo) WithContext(ctx context.Context) IAreaDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a areaDo) ReadDB() IAreaDo {
	return a.Clauses(dbresolver.Read)
}

func (a areaDo) WriteDB() IAreaDo {
	return a.Clauses(dbresolver.Write)
}

func (a areaDo) Session(config *gorm.Session) IAreaDo {
	return a.withDO(a.DO.Session(config))
}

func (a areaDo) Clauses(conds ...clause.Expression) IAreaDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a areaDo) Returning(value interface{}, columns ...string) IAreaDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a areaDo) Not(conds ...gen.Condition) IAreaDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a areaDo) Or(conds ...gen.Condition) IAreaDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a areaDo) Select(conds ...field.Expr) IAreaDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a areaDo) Where(conds ...gen.Condition) IAreaDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a areaDo) Order(conds ...field.Expr) IAreaDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a areaDo) Distinct(cols ...field.Expr) IAreaDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a areaDo) Omit(cols ...field.Expr) IAreaDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a areaDo) Join(table schema.Tabler, on ...field.Expr) IAreaDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a areaDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAreaDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a areaDo) RightJoin(table schema.Tabler, on ...field.Expr) IAreaDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a areaDo) Group(cols ...field.Expr) IAreaDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a areaDo) Having(conds ...gen.Condition) IAreaDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a areaDo) Limit(limit int) IAreaDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a areaDo) Offset(offset int) IAreaDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a areaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAreaDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a areaDo) Unscoped() IAreaDo {
	return a.withDO(a.DO.Unscoped())
}

func (a areaDo) Create(values ...*shop_model.Area) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a areaDo) CreateInBatches(values []*shop_model.Area, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a areaDo) Save(values ...*shop_model.Area) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a areaDo) First() (*shop_model.Area, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*shop_model.Area), nil
	}
}

func (a areaDo) Take() (*shop_model.Area, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*shop_model.Area), nil
	}
}

func (a areaDo) Last() (*shop_model.Area, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*shop_model.Area), nil
	}
}

func (a areaDo) Find() ([]*shop_model.Area, error) {
	result, err := a.DO.Find()
	return result.([]*shop_model.Area), err
}

func (a areaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*shop_model.Area, err error) {
	buf := make([]*shop_model.Area, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a areaDo) FindInBatches(result *[]*shop_model.Area, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a areaDo) Attrs(attrs ...field.AssignExpr) IAreaDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a areaDo) Assign(attrs ...field.AssignExpr) IAreaDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a areaDo) Joins(fields ...field.RelationField) IAreaDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a areaDo) Preload(fields ...field.RelationField) IAreaDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a areaDo) FirstOrInit() (*shop_model.Area, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*shop_model.Area), nil
	}
}

func (a areaDo) FirstOrCreate() (*shop_model.Area, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*shop_model.Area), nil
	}
}

func (a areaDo) FindByPage(offset int, limit int) (result []*shop_model.Area, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a areaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a areaDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a areaDo) Delete(models ...*shop_model.Area) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *areaDo) withDO(do gen.Dao) *areaDo {
	a.DO = *do.(*gen.DO)
	return a
}
